In [43]:
import pandas as pd

In [44]:
df=pd.read_csv("bonus.csv")

In [45]:
df.head(5)

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    1                   3    116
1     EMP_002            4                    8                  10    136
2     EMP_003            8                    4                   5    150
3     EMP_004            5                    4                   7    118
4     EMP_005            7                    5                   6    146

In [46]:
df.shape

(1000, 5)

In [47]:
from sklearn.model_selection import train_test_split

#Separate features and target

#features
X=df[["performance","years_of_experience","projects_completed"]]

#target
y=df[["bonus"]]

#ensuring df we use in Neural netrwork or Deep learning are in 2D array for compatibility ,
# and we later make into datatype of floats. all 
#this because the neural networks are heavily matrix form 
#DL is mainly on matrix and matrix operations as it has involvement of many neurons layers , each connected 
#with weights and so, we mainly use matrix operations to relate those layers and modulate weights.

#hence using df.values and later taking a float forms of those.

X=X.values
y=y.values


In [48]:
y

array([[116],
       [136],
       [150],
       [118],
       [146],
       [206],
       [102],
       [174],
       [200],
       [ 94],
       [152],
       [192],
       [168],
       [ 86],
       [158],
       [156],
       [ 94],
       [174],
       [106],
       [ 86],
       [122],
       [118],
       [176],
       [142],
       [190],
       [106],
       [150],
       [108],
       [162],
       [ 98],
       [194],
       [100],
       [156],
       [102],
       [180],
       [162],
       [164],
       [182],
       [ 88],
       [152],
       [204],
       [ 74],
       [176],
       [204],
       [222],
       [134],
       [ 64],
       [130],
       [124],
       [136],
       [ 68],
       [ 58],
       [118],
       [110],
       [194],
       [130],
       [ 78],
       [146],
       [136],
       [208],
       [ 80],
       [102],
       [ 98],
       [222],
       [ 66],
       [184],
       [ 78],
       [178],
       [118],
       [164],
       [190],
      

In [49]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [50]:
type(X_train)

numpy.ndarray

In [51]:
#Data is ready , Now train NN

# Train Neural Network

In [52]:
# the training of NN means optimizing the weights by running the nn in many epocs untill we acheive the 
# better prediction . So this weights training of nn , is first initiated by giving random weights at first 
# and then epochs are run to make them better .

# so we need to fix the randomness , as we may run the same code again and again and we cannot do that with 
# different randomness everytime., we call it seed for reproducibility

torch.manual_seed(0)

# Imagine PyTorch has an internal film reel of random numbers — billions of them — already decided by math.
#     [ ... 1.23, -0.45, 0.87, 2.34, -1.02, ... ]
# and 0 as seed means ,“Start reading this film from position #0.”
    

In [53]:
# NN in tensors only understands tensors, not the arrays or lists or df's.
# Since we have X_train,X_test and other outputs of train_test_Split in form of arrays , we will
# convert those to tensors

X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.float32)

# WIth this the data is ready, but we need neural network
# In pytorch, the neural network and its components are inherited from nn.Module class.
# So, we inherit the base componenets and neural network from it and use it in our own class where we provide 
# the required count of input features and how much of output neuron we can have in output

In [54]:
class BonusPredictor(nn.Module):
    def __init__(self):
        super().__init__() # calling constructor of nn.Module
        self.network=nn.Sequential(nn.Linear(3,1))  # saying that my nuralnetwrk is sequential and it has only one layer
        #that is linear layer, just takes 3 inputs , into 1 neuron and that one neuron gives its output

    def forward(self,x):
        return self.network(x)
    #this forward method is internally called by nn.Module when output = model(x) is ran, 
    # this method just takes x input from output = model(x), and forwards it to nn layers defined in constructor above.
    #     If you call self.network(x) directly.
    # You’d get a number, but you’d break:
    
    # 1 Backpropagation tracking , i.e automatic gradient computations will not happen
    
    # 2 Hooks
    
    # 3 Consistency with other modules
    
    


In [55]:
model=BonusPredictor()  # this is the brain

In [56]:
#we need a loss function which can say how far our predicted values are or how small or large the gradients are
loss_function=nn.MSELoss()  #Mean Square Loss

In [57]:
#Now we need optimizer, a mechanic which will tweek the brain (i.e weights) by learning the loss given by loss funciton

optimizer=optim.SGD(model.parameters(),lr=0.005)


# model.parameters() ,collects all the weights and biases
# from every layer in your model
# and gives them to the optimizer and optimizer adjusts them step by step using SGD with a learning rate of 0.005.”

In [58]:
# NOw since we defined brain, lossfucntion,optimizer, .
# We have to start the process of running the brain , i.e epochs

In [59]:
# i will use say 5000 epochs to start
epochs=5000

In [60]:
for epoch in range(epochs):
    predictions=model(X_train_tensor)  #this calls our BonusPrediction class
    loss=loss_function(predictions,y_train_tensor) #computes the differences btwn predicitons and training data

    #before doinf loss.backward, we need to clear if there are any gradients present of earlier epoch
    optimizer.zero_grad()  # zero's all past memory of gradients, & gets ready for fresh gradient calculation in every epoch
    
    #we have to calculate gradients
    loss.backward()

    #after calulating grads, we need to optimize the weights of brain
    optimizer.step()

    # Our code fininshes above line,
    #we are just see the loss, how that reduces it in every epoch.. just pringting every 100th epoch result
    if epoch%100 ==0:
        print(f"Epoch > {epoch} , Loss > {loss.item():.2f}")
    

Epoch > 0 , Loss > 20196.36
Epoch > 100 , Loss > 22.03
Epoch > 200 , Loss > 18.99
Epoch > 300 , Loss > 16.58
Epoch > 400 , Loss > 14.54
Epoch > 500 , Loss > 12.79
Epoch > 600 , Loss > 11.25
Epoch > 700 , Loss > 9.91
Epoch > 800 , Loss > 8.72
Epoch > 900 , Loss > 7.68
Epoch > 1000 , Loss > 6.76
Epoch > 1100 , Loss > 5.95
Epoch > 1200 , Loss > 5.24
Epoch > 1300 , Loss > 4.61
Epoch > 1400 , Loss > 4.06
Epoch > 1500 , Loss > 3.58
Epoch > 1600 , Loss > 3.15
Epoch > 1700 , Loss > 2.77
Epoch > 1800 , Loss > 2.44
Epoch > 1900 , Loss > 2.15
Epoch > 2000 , Loss > 1.89
Epoch > 2100 , Loss > 1.67
Epoch > 2200 , Loss > 1.47
Epoch > 2300 , Loss > 1.29
Epoch > 2400 , Loss > 1.14
Epoch > 2500 , Loss > 1.00
Epoch > 2600 , Loss > 0.88
Epoch > 2700 , Loss > 0.78
Epoch > 2800 , Loss > 0.68
Epoch > 2900 , Loss > 0.60
Epoch > 3000 , Loss > 0.53
Epoch > 3100 , Loss > 0.47
Epoch > 3200 , Loss > 0.41
Epoch > 3300 , Loss > 0.36
Epoch > 3400 , Loss > 0.32
Epoch > 3500 , Loss > 0.28
Epoch > 3600 , Loss > 0.25
Epo

In [64]:
#NOw we can see the loss has decreased to 0.05 at the end of 5000 epochs, and that is good.

#But this was just our training the brain, we have to test it using X_test and see losses with y_test now

#so evaluating our model or nn now

In [66]:
#Training is done, we will now switch our model to evalution mode

# Switch Model to Evaluation Mode from Training mode

In [67]:
model.eval()   #Switches model to evaluate mode from training model

BonusPredictor(
  (network): Sequential(
    (0): Linear(in_features=3, out_features=1, bias=True)
  )
)

# Model Evaluation 

In [68]:


with torch.no_grad():   # torch.no_grad > this tells to not create gradients now, as we are not in training phase
    test_predictions= model(X_test_tensor)
    test_loss=loss_function(test_predictions,y_test_tensor)
print(f"Test loss : {test_loss.item():.4f}")


Test loss : 0.0417


In [ ]:
#we end this notebook here, but we can still check our model with just one sample 
# to know how close the predicted(Y_predicted) and actual values (y_test) are

In [69]:
X_test_tensor[:3]  #“Take only the first 3 rows from this tensor. just test kar rahein hai bhai”

tensor([[ 8.,  9., 10.],
        [ 9.,  2.,  5.],
        [ 3.,  7.,  8.]])

In [70]:
test_predictions[:3]  #checking the predictions for first 3 rows

tensor([[189.9579],
        [150.1561],
        [113.7303]])

In [71]:
#compare the above with the actual y_test ones

y_test_tensor[:3]

tensor([[190.],
        [150.],
        [114.]])

In [72]:
# SO the predictions are very close to actual ones

# IMPORTANT

In [74]:
# The data set , i.e csv file was designed in a way , that Bonus feature was computed using other 3 columns
# but the weights which were given to make those values in Bonus column were

# w1=12 , w2=6 ,w3 =2 , bias=20

# SO, we took that csv here and trained the NeuralNwrk from scratch and asked it to optimize wights till we get our predictions closer
# to y_test

# , so after settling this model here, the weights of our model now should be near or same as the ones we used while
# creating that csv file

# Hence checking the weights of our model now.

for name , value in model.named_parameters():   #model.named_parameters() gives the weights & bias of NeuralNetwork
    print(f" Name {name} , Value {value}")  

 Name network.0.weight , Value Parameter containing:
tensor([[12.0335,  5.8423,  2.1879]], requires_grad=True)
 Name network.0.bias , Value Parameter containing:
tensor([19.2311], requires_grad=True)


In [ ]:
#  Name network.0.weight , Value Parameter containing:
# tensor([[12.0335,  5.8423,  2.1879]], requires_grad=True)
#  Name network.0.bias , Value Parameter containing:
# tensor([19.2311], requires_grad=True)

# the weights we got here and the bias are closer to 
# # w1=12 , w2=6 ,w3 =2 , bias=20
